### PR TITLE
Completed Readings Update

### PR DESCRIPTION
**Pull request by abm312**
updated readme to add readings checkmark

### CODE REVIEW

**Review by jiale0402 — APPROVED** [review]

**Comment by jiale0402** [comment]
good work!
by end of sunday I will make a new issue for you that outlines your next step of action, and in the mean time enjoy the break & happy thanksgiving!

**Comment by jiale0402** [comment]
and don't forgot to merge it. also u need to tag the issue that asked for this pr, namely #1

**Comment by abm312** [comment]
Thanks and have a great weekend!

**Comment by abm312** [comment]
Hi Jiale, dropping a reminder about this. @jiale0402

**Comment by jiale0402** [comment]
oh my bad, sry about this, i will make u an issue by EOD tmr

**Pull request merged**
